name: PMD Static Code Analyzer
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
steps:
  - uses: actions/setup-java@v2
    with:
      java-version: '11'
      distribution: 'temurin'
  - uses: pmd/pmd-github-action@v1
    with:
      rulesets: 'ruleset.xml'